PLUGIN_NAME=		opnrepo
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Opn-repo repository maintained by mimugmail
PLUGIN_MAINTAINER=	@mimugmail
PLUGIN_WWW=		https://github.com/mimugmail/opn-repo
PLUGIN_DEPENDS=		${PLUGIN_FLAVOUR:tl}

.include "../../Mk/plugins.mk"
