PLUGIN_NAME=		theme-solarized-community
PLUGIN_VERSION=		0.4
PLUGIN_REVISION=    1
PLUGIN_COMMENT=		Solarized theme - tracking OS dark mode
PLUGIN_MAINTAINER=	mihak09@gmail.com

.include "../../Mk/plugins.mk"
